export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const POST_USERS_REQUEST = 'POST_USERS_REQUEST';
export const POST_USERS_SUCCESS = 'POST_USERS_SUCCESS';
export const POST_USERS_FAILURE = 'POST_USERS_FAILURE';

export const UPDATE_USERS_REQUEST = 'UPDATE_USERS_REQUEST';
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS';
export const UPDATE_USERS_FAILURE = 'UPDATE_USERS_FAILURE';

export const PUBKEY = 'PUBKEY';
